Repository coala/artwork, pull requests merged in 2018-10, with the labels that each got.

#41 coala_color_svg: Add viewbox attribute
  artwork/logo/coala_color.svg
Labels: difficulty/low, status/ci-approved

#55 Update gitter link at README : coala-analyzer --> coala
  README.md
Labels: status/ci-approved

#57 coala_text: Add SVG of `coala.io` text
  artwork/logo/coala_text.svg
Labels: status/ci-approved

#52 Added ascii art for all releases
  artwork/deprecated_artwork/0_10_coala_PolarBear.txt
  artwork/deprecated_artwork/0_11_coala_BrewBear.txt
  artwork/deprecated_artwork/0_4_coala_eucalyptus.txt
  artwork/deprecated_artwork/0_5_coala_joey.txt
  artwork/deprecated_artwork/0_6_coala_honeybadger.txt
  artwork/deprecated_artwork/0_7_coala_baloo.txt
  artwork/deprecated_artwork/0_8_coala_grizzly.txt
  artwork/deprecated_artwork/0_9_coala_GlobalBear.txt
Labels: difficulty/newcomer, initiatives/gci, process/approved, process/pending_review, process/wip, size/S

#60 Change text in ad - coala-analyzer.org to coala.io
  artwork/ads/joinus.svg
Labels: difficulty/low, initiatives/gci, process/approved, process/pending_review, size/L

#54 coala-header.svg: Fix coala.io text rendering
  artwork/logo/coala-header.svg
Labels: process/pending review, size/S

#61 Add coala 404 page design
  artwork/popup_display/coala_404_page.svg
Labels: difficulty/low, initiatives/gci, process/approved, size/XL

#65 Change 55+ to 70+
  artwork/ads/basic.ai.svg
Labels: difficulty/low, initiatives/gci, process/approved, size/XS
