Repository coala/artwork, pull requests merged in 2018-11, with the labels that each got.

#66 Added new 404 artwork for GCI
  artwork/popup_display/coala404.svg
Labels: difficulty/low, initiatives/gci, process/approved, size/XS

#67 full_card.pdf: Change coala-analyzer.org
  artwork/business_cards/full_card.pdf
Labels: difficulty/low, initiatives/gci, process/approved, size/XS

#68 popup_display: Fix rendering issue
  artwork/popup_display/coala_stand_popup_display_horizontal.svg
Labels: difficulty/low, initiatives/gci, process/approved, size/XL

#69 Add ESLintBearLogo.svg
  artwork/logo/bears/ESLintBearLogo.svg
Labels: process/approved, size/M
